### ISSUE TITLE
Revisit EPMC licence detection

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#40]
- [x] use the url prefixes to detect the licence, so we don't need to know about all the variations on CC

- [x] if there is a licence, but it is not one we recognise, record it as "non-standard-licence" and do not send on to OAG

**Comment by richard-jones** [comment]
We also should probably look at normalising the text when we compare licence type strings, so that CC BY matches "cc-by".

**Comment by emanuil-tolev** [comment]
> if there is a licence, but it is not one we recognise, record it as "non-standard-licence" and do not send on to OAG

Er, ok, but if we do that we're not gonna get what's an author manuscript and what's not. Because author manuscripts mostly don't have an open license. So by not sending closed articles to OAG we also can't see if they're author manuscripts or not. Maybe this matters, maybe it doesn't (e.g. if being an author manuscript is one of Wellcome's conditions for Openness, it doesn't matter because the license isn't even open to begin with). See #16 too.

**Comment by richard-jones** [comment]
In response to the above: any item with a PMCID for which we haven't yet been able to determine the AAM status will be sent to OAG even if we have already detected a licence (closed or open), so this shouldn't be an issue.

Otherwise, this issue is now complete.
