### ISSUE TITLE
Tweaks to UI

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/oacwellcome#72]
@CecyMarden - if you want to list any changes to the UI required, just put them here and we'll pick them up.

**Comment by CecyMarden** [comment]
Thanks Richard, and Nevelina. 

1. Could you change the bit where it says wellcome so that instead it has our logo. You can find it here: http://www.wellcome.ac.uk/About-us/Logo-usage/WTP051580.htm

2. Could you make sure there is a tab (or something) on this page which will take users to a page which has a short blurb about what this is, plus the documentation we've discussed.

3. It would probably be a good idea to have some instructions somewhere e.g., you must upload a CSV file! If they're very short, then that could probably go on this page. 

4. Possibly there should also be an "Issues? Contact..." sentence as well.

**Comment by Nimphal** [comment]
I made a hotfix with the logo and the changed upload page title. Assigning back to @richard-jones

**Comment by richard-jones** [comment]
I've now added the documentation, and an explicit link to it from the upload page.

I've not added a contact field, because at this stage I'm not sure what the best way to manage this is - I'm not sure I want any one individual's email address on the page, and since there's only one user at the moment, I'm happy enough for us to be contacted directly.
